"use client";
import Link from "next/link";
import {useState} from "react";
import {Download,Video,Ticket,Users,ArrowUpRight,Check} from "lucide-react";
const offers=[
  {id:"digital",title:"Productos digitales",description:"Guías, plantillas, cursos y recursos descargables.",example:"Ejemplo: un desarrollador ofrece un kit de agentes de IA.",icon:Download},
  {id:"bookings",title:"Reservas y videollamadas",description:"Sesiones individuales, mentorías y consultas con horario.",example:"Ejemplo: un coach ofrece una sesión de objetivos.",icon:Video},
  {id:"tickets",title:"Tickets NFT",description:"Entradas a shows, talleres o pases con beneficios especiales.",example:"Ejemplo: un músico ofrece entrada y acceso backstage.",icon:Ticket},
  {id:"subscriptions",title:"Suscripciones",description:"Niveles de membresía con contenido y beneficios exclusivos.",example:"Ejemplo: un educador ofrece una comunidad mensual.",icon:Users},
];
export default function CreatorOfferSelection(){
  const [selected,setSelected]=useState<string[]>([]);
  return <section className="mt-6 rounded-2xl border border-violet-400/25 bg-[#171321] p-4 sm:p-7" aria-labelledby="card-offers-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-300">Las ofertas de tu card</p><h2 id="card-offers-title" className="mt-2 text-xl font-semibold text-white">¿Qué quieres ofrecer?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#b8b2c8]">Elige lo que encaje con tu trabajo. Puedes combinar varios tipos; tu profesión no limita las opciones.</p></div><span className="rounded-full border border-violet-400/20 px-3 py-1.5 text-[10px] text-violet-300">Vista previa de configuración</span></div>
    <fieldset className="mt-6 grid gap-3 sm:grid-cols-2"><legend className="sr-only">Tipos de oferta de la card</legend>{offers.map(({id,title,description,example,icon:Icon})=>{const active=selected.includes(id);return <label key={id} className={`flex cursor-pointer gap-4 rounded-xl border p-4 transition focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-violet-400 ${active?"border-violet-400/70 bg-violet-500/10":"border-white/10 bg-white/[.02] hover:border-violet-400/40"}`}><input type="checkbox" checked={active} onChange={()=>setSelected(active?selected.filter(v=>v!==id):[...selected,id])} className="mt-1 size-4 shrink-0 accent-violet-600"/><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-semibold text-white"><Icon size={18} className="text-violet-300" aria-hidden="true"/>{title}</div><p className="mt-2 text-xs leading-6 text-[#b8b2c8]">{description}</p><p className="mt-2 text-[11px] leading-5 text-zinc-400">{example}</p></div></label>})}</fieldset>
    <div className="mt-6 rounded-xl border border-white/10 bg-[#0b0b12] p-4"><p className="text-xs font-semibold text-violet-200">Así se organizarán las ofertas de tu card</p><div className="mt-3 space-y-2" aria-live="polite">{selected.length?offers.filter(o=>selected.includes(o.id)).map(({id,title,icon:Icon})=><div key={id} className="flex items-center justify-between gap-3 rounded-lg border border-violet-400/20 bg-violet-400/5 px-3 py-3 text-xs text-white"><span className="flex items-center gap-2"><Icon size={16} className="text-violet-300" aria-hidden="true"/>{title}</span><span className="flex items-center gap-1 text-[10px] text-violet-300"><Check size={12} aria-hidden="true"/>Por configurar</span></div>):<p className="text-xs leading-6 text-zinc-400">Selecciona una o más opciones para explorar su organización. También puedes tener una card sin ofertas.</p>}</div></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-[11px] leading-5 text-zinc-400">Selección de ejemplo, solo durante esta visita. No se guarda con el perfil ni cambia la card pública. Después, cada oferta necesitará nombre, precio y beneficios propios.</p><Link href="/dashboard/products" className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg sm:w-auto bg-violet-600 px-4 py-3 text-xs font-semibold text-white hover:bg-violet-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-300">Ver configuración de productos<ArrowUpRight size={14} aria-hidden="true"/></Link></div>
  </section>;
}
